# Generated by Django 5.2.3 on 2025-06-20 17:21

import core.enums
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("raw_text", models.TextField()),
                ("summary", models.TextField()),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            (core.enums.Sentiment["POSITIVE"], "Positive"),
                            (core.enums.Sentiment["NEUTRAL"], "Neutral"),
                            (core.enums.Sentiment["NEGATIVE"], "Negative"),
                        ],
                        default=core.enums.Sentiment["NEUTRAL"],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
